x-postgres-vars: &postgres-vars
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: launcher

services:
  db:
    image: postgres:14.2
    env_file: .env
    environment:
      <<: *postgres-vars
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "${APP_DB_PORT:-5432}:5432"
    expose:
      - 5432

  app:
    build: .
    volumes:
      - ./app:/code/app
    env_file: .env
    environment:
      <<: *postgres-vars
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
      UVICORN_LOG_LEVEL: ${LOGLEVEL:-debug}
      UVICORN_RELOAD: 'true'
    command: uvicorn app.main:app
    ports:
      - "${APP_PORT:-8000}:8000"
    expose:
      - 8000
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:
    name: launcher-data
